### PR TITLE
App icon: new assets

### PR DESCRIPTION
**Pull request by bertob**
This adds new app icon assets, but it's not hooked up to the build system yet as I don't know how to do that :)

image

It also keeps the old 24px icon around for LibreOffice, but pulls it out of the usual directory/naming so it's not used for the actual app.

See #75

### CODE REVIEW

**Comment by gkarsay** [comment]
Thank you! I will take care of this in 2 days. Meanwhile I wanted to ask for the license: The old one was CC BY-SA 3.0. Did you modify the old one or (shall I add you to the creators/copyright holders) or did you recreate it (replacing the other creators)? The license information is here: https://github.com/gkarsay/parlatype/blob/master/COPYING_CCBYSA

**Comment by bertob** [comment]
I didn't modify the old icons.

CC BY-SA 3.0 sounds good to me for the new stuff if that' what you'd prefer.

**Comment by gkarsay** [comment]
I have integrated it and will merge it as soon as you confirm that I can attribute it to you with your name and your email <your account at gnome.org>, the one used for your commit. I don't want to publish email addresses without confirmation. The license is CC BY-SA 4.0 (actually already in the svg file itself). Thanks again!

**Comment by bertob** [comment]
Sure, sounds good!

**Comment by gkarsay** [comment]
I commited your work with changed paths here: 9212766a58bbe8da5a5942555c9c2ecaff281903
License info: a613ab042c49ea602054ff8be96f7d4491f7a79d

**Pull request closed without merging**
